/*
 * Anggota Kelompok:
 * Eliza Riviera Rachmawati Jasin (1103130144)
 * Tifa Zulfa Yasmin (1103130280)
 * Lola Astri Nadita (1103130148)
 * Kelas IF 37-07
 * Bahasa pemograman yang digunakan : Bahasa Java dengan menggunakan NetBeans
 */
/**
 *
 * @author elizajasin
 */
package tugas2;

import java.awt.BorderLayout;
import java.awt.Color;
import java.lang.Math;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import org.jfree.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author elizajasin
 */
public class GUImosi extends javax.swing.JFrame {

    /**
     * Creates new form GUImosi
     */
    public GUImosi() {
        initComponents();
    }

    public int lgc (int a,int x,int c,int m){ //fungsi LGC
        int hasil = 0;
        hasil = (a*x+c)%m;
        return hasil;
    }
    
    public double pdf (double L, int m, int x){ //fungsi PDF
        double hasil = 0;
        hasil = -1/(double)L*Math.log(1-(double)x/(double)m);
        return hasil;
    }
    
    public double toJam (double n){ //fungsi convert ke jam
        int hasil = 0;
        hasil = (int)Math.round(n*60);
        return hasil;
    }
    
    public String wArrival (int f1, String jm, String mnt){ //fungsi waktu kedatangan
        int iJm = Integer.parseInt(jm);
        int iMnt = Integer.parseInt(mnt);
        int j = 0;
        int m = 0;
        m = iMnt + f1;
        j = iJm + m/60;
        if (m>60){
            m = m%60;
        }
        return Integer.toString(j)+':'+Integer.toString(m);
    }
    
    public String wService (int f2, String jm, String mnt){ //fungsi waktu pelayanan
        int iJm = Integer.parseInt(jm);
        int iMnt = Integer.parseInt(mnt);
        int j = 0;
        int m = 0;
        m = iMnt + f2;
        j = iJm + m/60;
        if (m>60){
            m = m%60;
        }
        return Integer.toString(j)+':'+Integer.toString(m);
    }
    
    public String wEnd (int f2, String jm, String mnt){ //fungsi waktu berakhirnya service
        int iJm = Integer.parseInt(jm);
        int iMnt = Integer.parseInt(mnt);
        int j = 0;
        int m = 0;
        m = iMnt + f2;
        j = iJm + m/60;
        if (m>60){
            m = m%60;
        }
        return Integer.toString(j)+':'+Integer.toString(m);
    }
    
    public int lAntri (String j1, String m1, String j2, String m2){ //fungsi lama waktu mengantri
        int M1 = Integer.parseInt(m1);
        int M2 = Integer.parseInt(m2);
        int J1 = Integer.parseInt(j1);
        int J2 = Integer.parseInt(j2);
        int h = M2-M1;
        if (h < 0){
            int H1 = J1*60+M1;
            int H2 = J2*60+M2;
            h = H2-H1;
        }
        return h;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        M = new javax.swing.JTextField();
        service = new javax.swing.JTextField();
        arrival = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Praktikan", "Inter Arrival", "Service Time", "Arrival Time", "Start Service", "End Service", "Queue Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Simulasi Antrian");

        jLabel2.setText("Eliza Riviera Rachmawati Jasin - 1103130144");

        jLabel3.setText("Tifa Zulfa Yasmin - 1103130280");

        jLabel4.setText("Lola Astri Nadita - 1103130148");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(137, 137, 137))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Input");

        jLabel7.setText("λ InterArrival Time");

        jLabel8.setText("λ Service Time");

        jLabel9.setText("M (Time of Simulation)");

        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });

        arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(M, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(service, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arrival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Output");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL3)
                            .addComponent(jL4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jL1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jL2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(60, 60, 60)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x0A = 4;
        int aA = 5;
        int cA = 5;
        int x0B = 2;
        int aB = 5;
        int cB = 3;
        double L1 = Integer.parseInt(arrival.getText());
        double L2 = Integer.parseInt(service.getText());
        int m = Integer.parseInt(M.getText());
        int[] a = new int[100];
        int[] b = new int[100];
        int[] f1 = new int[100];
        int[] f2 = new int[100];
        String[] wa = new String[100];
        String[] ws = new String[100];
        String[] we = new String[100];
        int[] la = new int[100];
        // kedatangan
        int x = x0A;
        int i = 0;
        while ((x != x0A) || ((x == x0A) && (i == 0))){
            i++;
            a[i] = lgc(aA,x,cA,m);
            x = a[i];
        }
        for (int j = 1;j <= i;j++){
            f1[j] = (int) toJam(pdf(L1,m,a[j]));
        }
        // service
        int y = x0B;
        int k = 0;
        while ((y != x0B) || ((y == x0B) && (k == 0))){
            k++;
            b[k] = lgc(aB,y,cB,m);
            y = b[k];
        }
        for (int j = 1;j <= k;j++){
            f2[j] = (int) toJam(pdf(L2,m,b[j]));
        }
        //waktu kedatangan
        String S;
        S = "0:0";
        for (int j = 1; j <= k; j++){
            wa[j] = wArrival(f1[j],S.substring(0, 1),S.substring(2));
            S = wa[j];
        }
        //waktu pelayanan
        S = wa[1];
        for (int j = 1; j <= k; j++){
            if (j == 1){
                ws[j] = S;
            }else{
                ws[j] = wService(f2[j-1],S.substring(0, 1),S.substring(2));
                S = ws[j];
            }
        }
        //waktu selesai
        S = ws[1];
        for (int j = 1; j <= k; j++){
            we[j] = wEnd(f2[j],S.substring(0, 1),S.substring(2));
            S = we[j];
        }
        //lama antri
        for (int j = 1; j <= k; j++){
            la[j] = lAntri(wa[j].substring(0, 1),wa[j].substring(2),ws[j].substring(0, 1),ws[j].substring(2));
        }
        //input table
        for (i=1; i<=k ; i++){
            Object[] row = {i,f1[i],f2[i],wa[i],ws[i],we[i],la[i]};
            DefaultTableModel model =(DefaultTableModel)table.getModel();
            model.addRow(row);
        }
        //banyaknya pelanggan
        jL1.setText("Banyaknya praktikan : "+Integer.toString(k));
        //rata2 waktu mengantri
        int sumLA = 0;
        for (int j = 1; j <= k; j++){
            sumLA = sumLA + la[j];
        }
        double rataLA = (double)sumLA/(double)k;
        jL2.setText("Rata2 waktu mengantri : "+String.format("%.2f",rataLA));
        //rata2 panjang antrian
        int z = Integer.parseInt(we[k].substring(0, 1))*60+Integer.parseInt(we[k].substring(2));
        int[] listA = new int[z+1];
        for (int j = 1; j <= k; j++){
            if (la[j] > 0){
                int q1 = Integer.parseInt(wa[j].substring(0, 1))*60+Integer.parseInt(wa[j].substring(2));
                int q2 = Integer.parseInt(ws[j].substring(0, 1))*60+Integer.parseInt(ws[j].substring(2));
                for (i = q1; i <= q2; i++){
                    listA[i]++;
                }
            }
        }
        int sumList = 0;
        for (int j = 0; j <= z; j++){
            sumList = sumList + listA[j];
        }
        double rataList = (double)sumList/(double)z;
        jL3.setText("Rata2 panjang antrian : "+String.format("%.2f",rataList));
        //lama waktu senggang
        boolean[] senggang = new boolean[z+1];
        for (int j = 1; j <= k; j++){
            if (j > 1){
                int q1 = Integer.parseInt(we[j-1].substring(0, 1))*60+Integer.parseInt(we[j-1].substring(2));
                int q2 = Integer.parseInt(ws[j].substring(0, 1))*60+Integer.parseInt(ws[j].substring(2));
                int t = q2-q1;
                if (t > 0){
                    for (i = q1; i <= q2; i++){
                        senggang[j] = true;
                    }
                }
            }
        }
        int sumSibuk = 0;
        for (int j = 0; j <= z; j++){
            if (senggang[j] == true){
                sumSibuk++;
            }
        }
        jL4.setText("Lama waktu senggang : "+Integer.toString(sumSibuk));
        
        //chart bar
        
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        for (int j = 0; j <= z; j++){
            String s = Integer.toString(j/60)+":"+Integer.toString(j%60);
            barChartData.setValue(listA[j], "", s);
        }
        
        JFreeChart barChart = ChartFactory.createBarChart("Grafik Praktikan", "Wakttu", "Praktikan", barChartData, PlotOrientation.VERTICAL, false, true, true);
        CategoryPlot barchrt = barChart.getCategoryPlot();
        barchrt.setRangeGridlinePaint(Color.BLUE);
        
        ChartFrame frame = new ChartFrame("Grafik Praktikan", barChart);
        frame.setVisible(true);
        frame.setSize(1000, 500);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MActionPerformed

    private void arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUImosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUImosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUImosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUImosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUImosi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField M;
    private javax.swing.JTextField arrival;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField service;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
